
SET(BOOST_VERSION 1_61_0)
SET (BOOST_ROOT "${VENDOR_PATH}/boost/boost_${BOOST_VERSION}")

MESSAGE(STATUS "BOOST root set to ${BOOST_ROOT}")

MACRO(FIND_BOOST_LIBRARY MYLIBRARY MYLIBRARYNAME)
    FIND_LIBRARY("${MYLIBRARY}_DEBUG"
        NAMES "${MYLIBRARYNAME}-gd-1_61"
        PATHS
        ${BOOST_ROOT}/lib64
        NO_DEFAULT_PATH
    )
    
    FIND_LIBRARY(${MYLIBRARY}
        NAMES "${MYLIBRARYNAME}-1_61"
        PATHS
        ${BOOST_ROOT}/lib64
        NO_DEFAULT_PATH
    )

    IF( NOT ${MYLIBRARY}_DEBUG)
        IF(MYLIBRARY)
            SET(${MYLIBRARY}_DEBUG ${MYLIBRARY})
         ENDIF(MYLIBRARY)
    ENDIF( NOT ${MYLIBRARY}_DEBUG)           
ENDMACRO(FIND_BOOST_LIBRARY LIBRARY LIBRARYNAME)

SET (BOOST_INCLUDE_DIR ${BOOST_ROOT})

FIND_BOOST_LIBRARY(BOOST_FILE_SYSTEM_LIBRARY libboost_filesystem-vc140-mt)
FIND_BOOST_LIBRARY(BOOST_SYSTEM_LIBRARY libboost_system-vc140-mt)
FIND_BOOST_LIBRARY(BOOST_SIGNAL_LIBRARY libboost_signals-vc140-mt)
FIND_BOOST_LIBRARY(BOOST_SERIALIZATION_LIBRARY libboost_serialization-vc140-mt)

SET(BOOST_FOUND "YES")
